### PR TITLE
Chef 14 Custom Resources

### PR DESCRIPTION
**Pull request by derekgroh**
* update version to 0.7.0
* remove depends on `windows` cookbook
* Compatible with Chef15+
* LWRP deprecated in favor of custom resources
* Delivery compatibility (Chef Automate)
* Improved testing flow with test kitchen to allow verify and test without the need to converge separately first
* added support for appveyor (still requires tweaking) CI/CD.

### CODE REVIEW

**Comment by derekgroh** [comment]
Addresses #11, #115

**Comment by anorstrom** [comment]
@derekgroh , we're facing the problem with WinRM not able to re-connect after dcpromo. The problem seems to have been solved in this code.

Will this pull request be merged, so that it becomes available via Chef Marketplace?

Thanks,
Andreas

**Comment by derekgroh** [comment]
@anorstrom I had completely forgotten about this, my apologies

**Comment by robin-martin** [comment]
Thanks, I was wondering about it too

**Comment by anorstrom** [comment]
Super, thanks @derekgroh :)

**Comment by anorstrom** [comment]
@derekgroh , we tried the new version and now got a more clear error, but still a problem with dcpromo where Kitchen gives an error when the DC restarts after dcpromo (dcpromo works good though and a new forest is created). 

> Failed to complete #converge action: [A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

We're using ec2 and tried the Transport and Provider settings you use in kitchen.yaml.

Do you have any other tip?

**Comment by derekgroh** [comment]
@anorstrom This is likely a timing issue. Try adjusting your `wait_for_retry` to a high (5 minutes+) to validate if it is a resource timing issue. I have not performed any validation against ec2.

**Comment by anorstrom** [comment]
@derekgroh looks like one issue sneaked into the windows_ad_group_member resource in this change (our cookbook fails on that resource). 

Attribute User_Name was removed but is still used on some places like line 22. Could hat be the problem?

**Comment by derekgroh** [comment]
@anorstrom yes, someone already pointed it out and is doing some testing for me. You can pull my master fork for the fix while we await feedback.

**Pull request merged**
