### PR TITLE
allow options to be set when joining a domain

### PR DESCRIPTION
**Pull request by aaronwalker**

### CODE REVIEW

**Comment by miguelaferreira** [comment]
Hi @aaronwalker 

I'll make time to test your PR tomorrow morning CET.
I'll let you know how that goes.

Thanks

**Comment by lolindirfalasion** [comment]
Well bugger, I removed the option command in ccde6d6e8f0213b33fe7a44eca973d8e3ecdbb19, good catch.  Readme should be updated to think link as we are using powershell options and not ds-add options: https://technet.microsoft.com/en-us/library/hh849798.aspx

**Comment by miguelaferreira** [comment]
Hi @aaronwalker

My first test was to create a domain controller and then a domain member with the same configs I have been using already.
```ruby
windows_ad_domain domain do
  action :join
  domain_user admin
  domain_pass admin_pass
end
```
That immediately breaks because I did not set any options for the join command.
```
==> test-dm: ================================================================================
==> test-dm: 
==> test-dm: Error executing action `run` on resource 'powershell_script[join_test.local]'
==> test-dm: ================================================================================
==> test-dm: 
==> test-dm: Mixlib::ShellOut::ShellCommandFailed
==> test-dm: ------------------------------------
==> test-dm: Expected process to exit with [0], but received '1'
==> test-dm: ---- Begin output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20150603-1040-1nmecje.ps1" ----
==> test-dm: STDOUT: 
==> test-dm: STDERR: Missing an argument for parameter 'Options'. Specify a parameter of type 'Microsoft.PowerShell.Commands.JoinOptions' and try again.
==> test-dm: ---- End output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20150603-1040-1nmecje.ps1" ----
==> test-dm: Ran "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20150603-1040-1nmecje.ps1" returned 1
==> test-dm: 
==> test-dm: Resource Declaration:
==> test-dm: ---------------------
==> test-dm: # In c:/var/chef/cache/cookbooks/windows_ad/providers/domain.rb
==> test-dm: 
==> test-dm:  92:       powershell_script "join_#{new_resource.name}" do
==> test-dm: 
==> test-dm:  93:         if node[:os_version] >= "6.2"
==> test-dm:  94:           cmd_text = "Add-Computer -DomainName #{new_resource.name} -Credential $mycreds -Force:$true -Restart"
==> test-dm:  95:           cmd_text << " -OUPath '#{ou_dn}'" if new_resource.ou
==> test-dm:  96:           cmd_text << " -Options #{new_resource.options.keys.join(',')}" if new_resource.options
==> test-dm:  97:           code <<-EOH
==> test-dm:  98:             $secpasswd = ConvertTo-SecureString '#{new_resource.domain_pass}' -AsPlainText -Force
==> test-dm:  99:             $mycreds = New-Object System.Management.Automation.PSCredential  ('#{new_resource.domain_user}', $secpasswd)
==> test-dm: 100:             #{cmd_text}
==> test-dm: 101:           EOH
==> test-dm: 102:         else
==> test-dm: 103:           cmd_text = "netdom join #{node[:hostname]} /d #{new_resource.name} /ud:#{new_resource.domain_user} /pd:#{new_resource.domain_pass}"
==> test-dm: 104:           cmd_text << " /ou:#{ou_dn}" if new_resource.ou
==> test-dm: 105:           cmd_text << " /reboot"
==> test-dm: 106:           code "#{cmd_text}"
==> test-dm: 107:         end
==> test-dm: 108:       end
==> test-dm: 
==> test-dm: Compiled Resource:
==> test-dm: ------------------
==> test-dm: # Declared in c:/var/chef/cache/cookbooks/windows_ad/providers/domain.rb:92:in `block in class_from_file'
==> test-dm: 
==> test-dm: powershell_script("join_test.local") do
==> test-dm:   action "run"
==> test-dm:   retries 0
==> test-dm:   retry_delay 2
==> test-dm:   default_guard_interpreter :powershell_script
==> test-dm:   command "join_test.local"
==> test-dm:   backup 5
==> test-dm:   returns 0
==> test-dm:   code "            $secpasswd = ConvertTo-SecureString 'Password1234###!' -AsPlainText -Force\n            $mycreds = New-Object System.Management.Automation.PSCredential  ('Administrator', $secpasswd)\n            Add-Computer -DomainName test.local -Credential $mycreds -Force:$true -Restart -Options \n"
==> test-dm:   interpreter "powershell.exe"
==> test-dm:   declared_type :powershell_script
==> test-dm:   cookbook_name "test_windows_ad"
==> test-dm: end
```

I've also looked at the resource file and the options are not required, and I agree with that.
```ruby
...
attribute :options, :kind_of => Hash, :default => {}
...
```
You did place a check in the provider to not add the options attribute to the command, but that check will always return `true` because you specified a default value in the resource file.
```ruby
cmd_text << " -Options #{new_resource.options.keys.join(',')}" if new_resource.options
```
You could make the check a bit more strict by saying something like:
```ruby
cmd_text << " -Options #{new_resource.options.keys.join(',')}" unless new_resource.options.empty?
```
I've tested that and it makes this first test pass.

**Comment by derekgroh** [comment]
clearing out old pull requests, if you feel this is still an issue, please open a new pull request against the current code base.

**Pull request closed without merging**
